### ISSUE TITLE
Cancel Change Colour Fails to Revert Colour

### ISSUE THREAD

**Issue by xargon666** [odest/iClock#3]
I very much like this project, and I have experimented with the settings some more and found a bug.

It appears that if a colour change is selected in the dailogue menus, and then the option is cancelled, it fails to revert to the previous colour. 

This seems to apply to both the border and text colour changes, so I expect it applies to all colour changes.

A possible soloution might be to have the current colour stored in a variable e.g. currentColour, and if cancel is selected the colour is set to currentColour.

I am running this in Windows 10 v22H2

**Comment by odest** [comment]
Thank you for your valuable feedback.

I have corrected the issue you mentioned. Now, when you change the **background color**, **border color**, **text color**, or **icon color**, the selected color will be applied if you choose it, but if you cancel, the previous color will be restored.

I look forward to hearing about any other issues you encounter.
